### ISSUE TITLE
Sometimes pedestal items do not load correctly

### ISSUE THREAD

**Issue by ScipioWright** [DaftBrit/NoitaArchipelago#101]
These show up if the flags == 0 print line plays.

Thankfully, the entity picker mod still allows me to check the item out without crashing.

The item had empty item_name and ui_description fields. So we should fill these up with something so that if the error happens again, it doesn't just crash your game.

Ideally, we also make it so this error never happens.

**Comment by heinermann** [comment]
Empty strings crash [GameTextGet](https://noita.wiki.gg/wiki/Modding:_Lua_API#GameTextGet), something I found out early on and documented. We should prioritize avoiding such a crash first before addressing the other issue that it isn't populated.

**Comment by ScipioWright** [comment]
Figured out how to avoid the crash. PR going up shortly.

**Comment by ScipioWright** [comment]
Fixed the issue in PR
