### ISSUE TITLE
Extra pick up message

### ISSUE THREAD

**Issue by ScipioWright** [DaftBrit/NoitaArchipelago#109]
Shows up when, presumably, the recorded index isn't the same as the ReceivedItems index, then it sends a Sync, which triggers GivePlayerOrbsOnSpawn.

It should be made to count up the number of items in the ReceivedItems message + 1 and set the index to that every time so this doesn't happen.

**Comment by heinermann** [comment]
We should fix this as a high priority before the release since it causes many resyncs that create way more packets than needed.

**Comment by ScipioWright** [comment]
Fix in PR
