### ISSUE TITLE
[Bug]: "Can't parse JSON, trailing garbage"

### ISSUE THREAD

**Issue by madisonsilver** [DaftBrit/NoitaArchipelago#162]
### Which of these are true?

- [ ] The archipelago logo did not appear in the bottom right after starting a new game.
- [ ] I could not connect to the Archipelago server.
- [ ] I had other mods loaded with Archipelago (list all of them below).

### What happened?

After connecting to the multiworld, an error message would occasionally pop up saying "can't parse JSON, trailing garbage" or, rarely, "JSON package groks only UTF-8, sorry".  This didn't prevent sending/receiving items, and didn't seem to cause any non-graphical/UI issues.

### Upload your `logger.txt` file here.

[logger.txt](https://github.com/DaftBrit/NoitaArchipelago/files/12503260/logger.txt)

### Death Link

No

### Traps

Yes

### Victory Condition

Pure Ending

### Path Option

Main World

### Hidden Chests per Biome

1

### Pedestal Checks per Biome

1

### Orbs as Location Checks

Main World

### Bosses as Location Checks

Main Path

**Comment by ScipioWright** [comment]
The bug appears to be some kind of keep alive thing (thanks silvris) probably, since it consistently happens every 20 seconds while connected. Trying to investigate it, but pretty lost on what's actually doing this keep alive here.

**Comment by heinermann** [comment]
Do we have some example packet data?

**Comment by madisonsilver** [comment]
I tried to record some packet data via Fiddler but wasn't able to get it to
work.  I can try again later if it would help.
