### ISSUE TITLE
[Bug]: Orb of knowledge despawned

### ISSUE THREAD

**Issue by skoelio** [DaftBrit/NoitaArchipelago#176]
### Which of these are true?

- [ ] The archipelago logo did not appear in the bottom right after starting a new game.
- [ ] I could not connect to the Archipelago server.
- [X] I had other mods loaded with Archipelago (list all of them below).

### What happened?

Other mods: 
Dead isn't dead
Repulsion perk tweak
menacing berserker
megumin player
edit wands always
glowing health upgrades
glowing chests
actually unlimited spells
better bounce
conga's cats
advanced spell inventory

While digging with black hole and teleporting up from the bottom of wizard's den an orb spawned then disappeared, in its place was a tier 1 green shuffle wand but colored black. I started to clear the whole area and wasn't able to find the orb in the whole wizard's den or anywhere on the surface.

### Death Link

None

### Traps

Yes

### Victory Condition

Pure Ending

### Path Option

Main Path

### Hidden Chests per Biome

3

### Pedestal Checks per Biome

6

### Orbs as Location Checks

Main World

### Bosses as Location Checks

None

**Comment by ScipioWright** [comment]
If you have a log file, please attach that. Should be in your Noita folder

**Comment by skoelio** [comment]
[logger.txt](https://github.com/user-attachments/files/16919514/logger.txt)

**Comment by ScipioWright** [comment]
It sounds to me like you got far enough away from the Orb that it despawned (since Noita unloads stuff when you get far enough away), and it hasn't been set up to respawn orbs received through Archipelago when you get too far away (because I assumed people would always pick up orbs immediately as they spawn). Starting a new game should just re-give it to you.

**Comment by skoelio** [comment]
Yeah, you are absolutely right, didn't know that was a thing
