### ISSUE TITLE
Big red text on screen for major errors

### ISSUE THREAD

**Issue by heinermann** [DaftBrit/NoitaArchipelago#4]
It's not clear whether the game is connected to Archipelago or not (i.e. when you type incorrect server info), so when a connection failure occurs there should be a permanent red text indicating the major error that is preventing the game from being played.

**Comment by DaftBrit** [comment]
What I was hoping for was a method to use the inbuilt GamePrint function, as this acts similar to a console feed in the bottom left hand corner and currently states when a connection is successful. However this fades far too quickly to be of any great use and magic numbers dont appear to have a configuration option for fade time. It might be better to replace all messaging functions with a customui element we have more control over.

The cheat gui mod makes great use of the custom ui methods and would probably be a good reference.

**Comment by ScipioWright** [comment]
I'll try to work on this. Slightly tempted to do what the Noita devs did for the recent update and have it spawn a big, flaming "CONNECTION FAILED" message above the player, but will probably just have it display the big red text.

**Comment by heinermann** [comment]
I was thinking we could just do an icon in the lower right or lower left that shows the connection state at all times.

**Comment by ScipioWright** [comment]
That works too, I'll figure out how UI shenanigans work. If they are dependent on game resolution I'm going to scream, though.

**Comment by ScipioWright** [comment]
Current status of this issue: When starting up the game with the mod enabled, the game will give you a perk with an archipelago icon with a red X through it (with appropriate name and description). When you successfully receive the "Connected" message, it removes that perk and replaces it with a perk with the same icon without the X through it.

Next step is to do something to check whether you're still connected occasionally, and adjust accordingly.

**Comment by heinermann** [comment]
We now have an actual hover-icon in the bottom right.

**Comment by heinermann** [comment]
Going to resolve this since the red X is visible enough I think.
