### ISSUE TITLE
When receiving multiple items in async after continuing, they all spawn in the same spot under you

### ISSUE THREAD

**Issue by ScipioWright** [DaftBrit/NoitaArchipelago#46]
This makes the wands have the same seed. Ideally, we should offset them by at least a pixel or two, just to vary them without moving them too far, since moving them might get them stuck.

**Comment by heinermann** [comment]
Also happens when other players complete their goals and release their items.

**Comment by ScipioWright** [comment]
Fixed by implementing some randomness when delivering items. They'll spawn +/- 2 pixels horizontally and vertically, reducing the chance of duplicates significantly
