### ISSUE TITLE
When picking up someone else's trap off of a pedestal, it spawns a trap for you too

### ISSUE THREAD

**Issue by ScipioWright** [DaftBrit/NoitaArchipelago#51]
Really I should've seen this coming...

**Comment by heinermann** [comment]
Lmao

**Comment by heinermann** [comment]
We could distinguish them by making them separate items, or by checking if it's for us in the script

**Comment by ScipioWright** [comment]
I'm going to do it in the script. At the end of the create_ap_entity_from_flags script, just before the return I'm going to add a "if this is a trap and is our item then add a lua component for ap_badtimes.lua". Just gotta test and make sure it works then we're good to go.

**Comment by ScipioWright** [comment]
Fixed, closed.
