### ISSUE TITLE
Too many spell refreshers

### ISSUE THREAD

**Issue by heinermann** [DaftBrit/NoitaArchipelago#56]
Playing only a game with yourself, there are too many spell refreshers in shops. There should be fewer spell refreshers and possibly more wands and potions.

**Comment by ScipioWright** [comment]
Currently, the sum of the weights in Items.py is 233. Since spell refreshes are set to 30, ~13% of the items should be spell refreshes. So yeah, agreed. Maybe let's go down to 20, so that it's only 9% of them, or 15 for 7%.

**Comment by heinermann** [comment]
Seems much better now.
