### ISSUE TITLE
Orbs get removed from orb count on continue

### ISSUE THREAD

**Issue by ScipioWright** [DaftBrit/NoitaArchipelago#61]
When continuing a game, your orb count is reduced to 0 after receiving AP orbs.

**Comment by ScipioWright** [comment]
Issue has been worked around in a recently merged PR. On new game and on continue, an item is sent to you that gets a number of different-valued OrbComponents based on how many orbs you have found so far. So if you have gotten 6 orbs so far, it'll auto-give this item with OrbComponents valued 20, 21, 22, etc. This does, in fact, work to increase your orb count for that session.

Also, orbs no longer spawn in the mountain on new game. Instead, your health is increased based on the number of orbs + the number of life up hearts you've received so far. I hope you don't put off Kolmi for too long...

**Comment by heinermann** [comment]
> I hope you don't put off Kolmi for too long...

:)
