### ISSUE TITLE
Proposal for potions shattering immediately

### ISSUE THREAD

**Issue by heinermann** [DaftBrit/NoitaArchipelago#78]
## Proposal
Make AP potions out of an indestructible material that looks like glass, that becomes normal potion glass after a timeout or when picked up. Then the potions can spawn and settle without getting shattered, but still shatter later, making the experience more fair for the player.

**Comment by ScipioWright** [comment]
As much as I like the potions shattering immediately, that's reasonable enough. Maybe just a short timeout though, so if you're flying in the air or something and they fall at least half a screen they'll still shatter. Or it can be a few seconds if you want to avoid that too, just might look a little weird at that point.

**Comment by heinermann** [comment]
It might be possible to make it so that it waits until it stops moving before it gets changed, this way it's not really timeout based and instead based on movement from the point of spawning.

**Comment by ScipioWright** [comment]
This issue has been fixed and may be closed

**Comment by heinermann** [comment]
I think the timer thing is good for now, it may still be an issue if a potion is dropped from high up but we'll see with more testing. If it's still an issue we can revisit this again.
