### ISSUE TITLE
Money sound when receiving money

### ISSUE THREAD

**Issue by ScipioWright** [DaftBrit/NoitaArchipelago#84]
Currently, when gold is delivered, it is just added directly to your "wallet". It should make the gold pick up sound when you receive it. I don't know how to add the enhancement label to this.

**Comment by heinermann** [comment]
`gold_pickup.xml` has

```xml
    <AudioComponent
      file="data/audio/Desktop/event_cues.bank"
      event_root="event_cues/goldnugget">
    </AudioComponent>
```

so we can play it with this I think?

```lua
GamePlaySound("data/audio/Desktop/event_cues.bank", "event_cues/goldnugget", GameGetCameraPos())
```

Not sure if x and y returned by GameGetCameraPos expands into the argument list or not.
