### ISSUE TITLE
[Bug]: Bad trap name on other person's trap

### ISSUE THREAD

**Issue by ScipioWright** [DaftBrit/NoitaArchipelago#87]
### Which of these are true?

- [ ] The archipelago logo did not appear in the bottom right after starting a new game.
- [ ] I could not connect to the Archipelago server.
- [ ] I had other mods loaded with Archipelago (list all of them below).

### What happened?

Trap name showed up as [Name]'s $ap_trapname2

### Upload your `logger.txt` file here.

[logger.txt](https://github.com/DaftBrit/NoitaArchipelago/files/11238201/logger.txt)
![image](https://user-images.githubusercontent.com/24858499/232181145-5218ff33-ef43-45f1-a359-9f58374a10f1.png)

### Death Link

None

### Traps

Yes

### Victory Condition

Greed Ending

### Path Option

Main Path

### Orbs as Location Checks

None

### Bosses as Location Checks

None

**Comment by heinermann** [comment]
Ah I see, there should be a resolution on the translation beforehand. I just assumed that it would get resolved later.
