### ISSUE TITLE
AP items in Holy Mountains are too costly

### ISSUE THREAD

**Issue by heinermann** [DaftBrit/NoitaArchipelago#91]
The intent was to make them similar to wand prices, but they are way more expensive.

<img width="781" alt="2023-04-15 15_27_14-Noita - Build Mar 11 2023 - 14_09_24" src="https://user-images.githubusercontent.com/1966366/232255751-dbb12c7a-c5f6-42d5-8825-08193ce877e6.png">

**Comment by heinermann** [comment]
Too costly early game, too cheap late game (I think).

**Comment by ScipioWright** [comment]
Observed shop prices per biome:

Shop 1: 140-410

Shop 2: 110-410

Shop 3: 530-810

Secret Shop: 310-340 (spells)

Shop 4: 530-800

Shop 5: 1310-1460

Shop 6: 2000-2280

Shop 7: 4340-4580

**Comment by ScipioWright** [comment]
PR for this fix has been made

**Comment by heinermann** [comment]
Just a thought but we could make junk items cheaper and progression items more expensive.
